site_name: FEniCS Course
theme:
  name: readthedocs
  highlightjs: true
  logo: img/logo.svg
  icon:
    admonition:
      history: img/favicon.ico

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
copyright: Copyright &copy; 2023 - 2024 ⦿ <a href="https://abhigupta.io">Abhinav Gupta</a> 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Introduction:
      - Motivation: 1_introduction/1_motivation.md
      - Installation: 1_introduction/2_installation.md
      - Quickstart: 1_introduction/3_quickstart.md
      - SalomeTutorial: 1_introduction/5_salome_tutorial.md
      - FAQ: 1_introduction/4_faq.md  
  - Day 1:
    - Tutorials:
        - Tutorial 1-1 Solving linear Poisson's equation: 2_notebooks/day-1/tutorials/1_linear_poisson.md 
        - Tutorial 1-2 Visualization: 2_notebooks/day-1/tutorials/2_visualization.md 
    - Exercises:
      - Exercise 1-1 Built in meshes: 2_notebooks/day-1/exercises/1_built_in_mesh.md 
      - Exercise 1-2 Boundary conditions: 2_notebooks/day-1/exercises/2_boundary_conditions.md 
      - Exercise 1-3 Expressions: 2_notebooks/day-1/exercises/3_expressions.md 
      - Exercise 1-4 Spacially varying properties: 2_notebooks/day-1/exercises/4_spacially_varying_properties.md 
      - Exercise 1-5 Convergence: 2_notebooks/day-1/exercises/5_convergence.md 
  - Day 2:
    - Tutorials:
        - Tutorial 2-1 Solving non-linear Poisson's equation using Picard Iteration: 2_notebooks/day-2/tutorials/1_non_linear_poisson_picard.md 
        - Tutorial 2-3 Solving non-linear Poisson's equation using Newton Iteration: 2_notebooks/day-2/tutorials/2_non_linear_poisson_newton.md 
        - Tutorial 2-3 Newton method with Manual Differentiation: 2_notebooks/day-2/tutorials/3_non_linear_poisson_newton_manual_diff.md 
        - Tutorial 2-4 Newton method with Automatic Differentiation: 2_notebooks/day-2/tutorials/4_non_linear_poisson_newton_auto_diff.md 
    - Exercises:
      - Exercise 2-1 2D and 3D Domains: 2_notebooks/day-2/exercises/1_2d_3d_domains.md 
      - Exercise 2-2 Boundary Conditions: 2_notebooks/day-2/exercises/2_boundary_conditions.md 
      - Exercise 2-3 Non-Linearity and Tolerances: 2_notebooks/day-2/exercises/3_non_linearity_tolerances.md 
      - Exercise 2-4 Manual vs Auto differentiation: 2_notebooks/day-2/exercises/4_manual_auto_differentiation.md 
  - Day 3:
    - Tutorials:
        - Tutorial 3-1 Beam bending: 2_notebooks/day-3/tutorials/1_beam_bending.md 
        - Tutorial 3-2 Loads and boundary conditions: 2_notebooks/day-3/tutorials/2_load_and_boundary_conditions.md 
        - Tutorial 3-3 Solver design: 2_notebooks/day-3/tutorials/3_solver.md 
    - Exercises:
      - Exercise 3-1 3D Uniaxial: 2_notebooks/day-3/exercises/1_3d_uniaxial.md 
      - Exercise 3-2 Plane Stress v/s Plane strain: 2_notebooks/day-3/exercises/2_plane_stress_strain.md 
      - Exercise 3-3 Effect of solver design: 2_notebooks/day-3/exercises/3_solver_design.md 
      - Exercise 3-4 Stress Concentration: 2_notebooks/day-3/exercises/4_stress_concentration.md 
  - Day 4:
    - Tutorials:
        - Tutorial 4-1 Solving hyper elasticity in FEniCS: 2_notebooks/day-4/tutorials/1_hyper_elastic.md 
        - Tutorial 4-1 Pseudo time stepping in hyper elasticity: 2_notebooks/day-4/tutorials/2_load_displacement.md 
    - Exercises:
      - Exercise 4-1 Mooney rivlin material model: 2_notebooks/day-4/exercises/1_mooney-rivlin.md 
      - Exercise 4-2 Comparison between elastic and hyperelastic solution: 2_notebooks/day-4/exercises/2_comparison.md 
  - Day 5:
    - Tutorials:
        - Tutorial 5-1 Thermoelasticity: 2_notebooks/day-5/tutorials/1_thermoelasticity.md 
        - Tutorial 5-2 Multi-material domains: 2_notebooks/day-5/tutorials/2_multi_material.md 
        - Tutorial 5-3 Transient analysis: 2_notebooks/day-5/tutorials/3_transient_analysis.md 
    - Exercise:
      - Exercise 5-1 Bi-metallic quasi static analysis: 2_notebooks/day-5/exercises/1_bi_metallic_quasi_static.md 
      - Exercise 5-2 Transient thermo-mechanical analysis: 2_notebooks/day-5/exercises/2_thermo_mechanical_transient.md  


