site_name: FEniCS Workshop
theme:
  name: readthedocs
  highlightjs: true
  logo: img/logo.svg
  icon:
    admonition:
      history: img/favicon.ico

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
copyright: Copyright &copy; 2023 - 2024 ⦿ <a href="https://abhigupta.io">Abhinav Gupta</a>

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Introduction:
      - Motivation: 1_introduction/1_motivation.md
      - Installation: 1_introduction/2_installation.md
      - Quickstart: 1_introduction/3_quickstart.md
      - FAQ: 1_introduction/4_faq.md
  - Tutorials:
      - Poissons Equation: 2_tutorials/1_linear_poisson.md
  - Exercises:
      - API: 3_exercises/1_getting_started.md
